[package]
name = "mimosa"
description = "CLI and library to manage passwords stored in OS-native keyrings"
version = "1.0.0"
authors = ["soywod <pimalaya.org@posteo.net>"]
edition = "2024"
rust-version = "1.87"
license = "AGPL-3.0-only"
categories = ["command-line-utilities", "authentication"]
keywords = ["cli", "password", "keyring", "keychain", "credential"]
homepage = "https://pimalaya.org"
documentation = "https://docs.rs/mimosa/latest/mimosa"
repository = "https://github.com/pimalaya/mimosa"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[features]
default = ["dbus-secret-service", "apple-keychain", "windows-credential-manager"]
dbus-secret-service = ["dep:dbus-secret-service-keyring-store"]
zbus-secret-service = ["dep:zbus-secret-service-keyring-store"]
keyutils = ["dep:linux-keyutils-keyring-store"]
apple-keychain = ["dep:apple-native-keyring-store"]
windows-credential-manager = ["dep:windows-native-keyring-store"]
vendored = ["dbus-secret-service-keyring-store?/vendored"]

[build-dependencies]
pimalaya-cli = { version = "0.0.1", default-features = false, features = ["build"] }

[target.'cfg(target_os = "macos")'.dependencies]
apple-native-keyring-store = { version = "1", default-features = false, features = ["keychain"], optional = true }

[target.'cfg(target_os = "linux")'.dependencies]
linux-keyutils-keyring-store = { version = "1", optional = true }

[target.'cfg(any(target_os = "linux", target_os = "freebsd"))'.dependencies]
dbus-secret-service-keyring-store = { version = "1", default-features = false, features = ["crypto-rust"], optional = true }
zbus-secret-service-keyring-store = { version = "1", default-features = false, features = ["rt-async-io-crypto-rust"], optional = true }

[target.'cfg(target_os = "windows")'.dependencies]
windows-native-keyring-store = { version = "1", optional = true }

[dev-dependencies]
toml = "0.8"

[dependencies]
anyhow = "1"
clap = { version = "4.4", features = ["derive", "wrap_help"] }
keyring-core = "1"
log = "0.4"
pimalaya-cli = { version = "0.0.1", default-features = false, features = ["terminal"] }
pimalaya-config = { version = "0.0.1", default-features = false, features = ["toml"] }
secrecy = "0.10"
serde = { version = "1", features = ["derive"] }

# [patch.crates-io]
# pimalaya-cli.path = "../cli"
# pimalaya-config.path = "../config"

[patch.crates-io]
pimalaya-cli.git = "https://github.com/pimalaya/cli"
pimalaya-config.git = "https://github.com/pimalaya/config"
